apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-frontend
  namespace: argocd
spec:
  source:
    helm:
      values: |
        productEndpointOverride: /production/api/products
        productHealthEndpointOverride: /production/health/products
        auditsEndpointOverride: /production/api/audits
        auditsHealthEndpointOverride: /production/health/audits
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/use-regex: "true"
            nginx.ingress.kubernetes.io/rewrite-target: /$2
          hosts:
            - host:
              paths:
              - path: /production(/|$)(.*)
                pathType: Prefix