apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: frontend-versions.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-frontend
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: octopub-production