argocd_application: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-frontend
  namespace: argocd
  labels:
    environment: unknown
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.octopus: ""
spec:
  project: default
  source:
    chart: nginx
    repoURL: oci://registry-1.docker.io/bitnamicharts
    targetRevision: 15.1.4
    helm:
      releaseName: nginx
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx
  syncPolicy:
    automated: {}