apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '#{ArgoCD.Project.Name | ToLower | Replace "[^a-zA-Z0-9]" "-"}'
  namespace: argocd
  labels:
    environment: unknown
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.octopus: ""
spec:
  project: default
  source:
    chart: nginx
    repoURL: oci://registry-1.docker.io/bitnamicharts
    targetRevision: 15.1.4
    helm:
      releaseName: '#{ArgoCD.Project.Name | ToLower | Replace "[^a-zA-Z0-9]" "-"}'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: '#{ArgoCD.Project.Name | ToLower | Replace "[^a-zA-Z0-9]" "-"}'
  syncPolicy:
    automated: {}