apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-audits
    patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: 0.1.170
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-products
    patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: 0.1.170
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-frontend
    patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: 0.1.170