apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: frontend-versions.yaml
  - path: frontend-values.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-frontend
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: octopub-development
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-frontend
    patch: |-
      - op: replace
        path: /metadata/labels/environment
        value: development
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-frontend
    patch: |-
      - op: replace
        path: /metadata/name
        value: octopub-frontend-development