apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: audits-versions.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-audits
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: octopub-production
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-audits
    patch: |-
      - op: replace
        path: /metadata/labels/environment
        value: production
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-audits
    patch: |-
      - op: replace
        path: /metadata/name
        value: octopub-audits-production