version: '3'
networks:
  octopus:
    external: false
volumes:
  giteadb:
    driver: local
  gitea:
    driver: local
  terraformdb:
    driver: local
  sqlvolume:
    driver: local
  repository:
    driver: local
  artifacts:
    driver: local
  taskLogs:
    driver: local
  cache:
    driver: local
  import:
    driver: local
services:
  octopus:
    ports:
      - "127.0.0.1:18080:8080"
    environment:
      - ADMIN_API_KEY=API-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=octopusguides@gmail.com
      - ADMIN_PASSWORD=Password01!
      - ACCEPT_EULA=Y
      - DB_CONNECTION_STRING=Server=mssql,1433;Database=Octopus;User Id=SA;Password=Password01!;ConnectRetryCount=6
      - CONNSTRING=Server=mssql,1433;Database=Octopus;User Id=SA;Password=Password01!;ConnectRetryCount=6
      - MASTER_KEY=6EdU6IWsCtMEwk0kPKflQQ==
      - OCTOPUS_SERVER_BASE64_LICENSE
    image: octopusdeploy/octopusdeploy
    networks:
      - octopus
    depends_on:
      - mssql
    volumes:
      - repository:/repository
      - artifacts:/artifacts
      - taskLogs:/taskLogs
      - cache:/cache
      - import:/import
      - /var/run/docker.sock:/var/run/docker.sock
  mssql:
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password01!
      MSSQL_PID: Express
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - octopus
    volumes:
      - sqlvolume:/var/opt/mssql
  gitea:
    image: gitea/gitea:1.19.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=giteadb:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__security__INSTALL_LOCK=true # https://discourse.gitea.io/t/unattended-gitea-installation-from-the-cli/3373/19
    restart: always
    networks:
      - octopus
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:222:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  giteadb:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - octopus
    volumes:
      - giteadb:/var/lib/postgresql/data
  terraformdb:
    image: postgres:14
    container_name: terraformdb
    ports:
      - "127.0.0.1:15432:5432"
    restart: always
    environment:
      POSTGRES_USER: terraform
      POSTGRES_PASSWORD: terraform
    networks:
      - octopus
    volumes:
      - terraformdb:/var/lib/postgresql/data