apiVersion: apps/v1
kind: Deployment
metadata:
  name: octoargosync
  namespace: argocd
  labels:
    app: octoargosync
spec:
  selector:
    matchLabels:
      app: octoargosync
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: octoargosync
    spec:
      containers:
        - name: octoargosync
          image: octopussamples/octoargosync
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ARGOCD_SERVER
              value: argocd-server.argocd.svc.cluster.local:443
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: octoargosync-secret
                  key: argotoken
            - name: OCTOPUS_SERVER
              value: http://octopus:8080
            - name: OCTOPUS_SPACE_ID
              value: Spaces-4
            - name: OCTOPUS_API_KEY
              value: API-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
---
apiVersion: v1
kind: Service
metadata:
  name: octoargosync
  namespace: argocd
spec:
  selector:
    app: octoargosync
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
