apiVersion: apps/v1
kind: Deployment
metadata:
  name: octoargosync
  labels:
    app: octoargosync
spec:
  selector:
    matchLabels:
      app: octoargosync
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: octoargosync
    spec:
      containers:
        - name: octoargosync
          image: octopussamples/octoargosync
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: octoargosync
spec:
  selector:
    app: octoargosync
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
