apiVersion: v1
kind: Namespace
metadata:
  name: octopub-development
---
apiVersion: v1
kind: Namespace
metadata:
  name: octopub-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: octopub-production
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: octopub
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: octopub-products
            environment: development
          - name: octopub-products
            environment: test
          - name: octopub-products
            environment: production
          - name: octopub-audits
            environment: development
          - name: octopub-audits
            environment: test
          - name: octopub-audits
            environment: production
          - name: octopub-frontend
            environment: development
          - name: octopub-frontend
            environment: test
          - name: octopub-frontend
            environment: production
  template:
    metadata:
      name: '{{name}}-{{environment}}-parent'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: http://gitea:3000/octopuscac/argo_cd.git
        targetRevision: HEAD
        path: argocd/{{name}}/overlays/{{environment}}
      destination:
        server: "https://kubernetes.default.svc"
        namespace: argocd