apiVersion: v1
kind: Namespace
metadata:
  name: nginx-development
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-production