apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/production

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-audits
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: octopub-production
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-products
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: octopus-production
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-frontend
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: octopub-production
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Namespace
      name: octopub
    patch: |-
      - op: replace
        path: /name
        value: octopub-production