apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: products-versions.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-products
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: octopub-development
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: octopub-products
    patch: |-
      - op: replace
        path: /metadata/labels/environment
        value: development