name: Build Test Stack
'on':
  workflow_dispatch: {}
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: curl --silent https://raw.githubusercontent.com/OctopusSolutionsEngineering/EnterprisePatternsReferenceImplementation/main/ubuntu-dependencies.sh | bash
      - name: Build Stack
        env:
          OCTOPUS_SERVER_BASE64_LICENSE: ${{secrets.OCTOPUS_SERVER_BASE64_LICENSE}}
        run: ./initdemo.sh