name: Build Test Stack
'on':
  workflow_dispatch: {}
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: curl --silent https://raw.githubusercontent.com/OctopusSolutionsEngineering/EnterprisePatternsReferenceImplementation/main/ubuntu-dependencies.sh | sudo bash
      - name: Build Stack
        env:
          OCTOPUS_SERVER_BASE64_LICENSE: ${{secrets.OCTOPUS_SERVER_BASE64_LICENSE}}
          TF_VAR_docker_username: ${{secrets.DOCKERHUB_USERNAME}}
          TF_VAR_docker_password: ${{secrets.DOCKERHUB_TOKEN}}
        run: ./initdemo.sh
      - name: Test projects exist
        run: |
          curl --fail -H "X-Octopus-ApiKey: API-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" http://localhost:18080/api/Spaces-1/Projects/hello-world
          if [[ $? != "0" ]]; then exit 1; fi