apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: chart_version.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: '#{ArgoCD.Project.Name | ToLower | Replace "[^a-zA-Z0-9]" "-"}'
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: '#{ArgoCD.Project.Name | ToLower | Replace "[^a-zA-Z0-9]" "-"}-development'
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: '#{ArgoCD.Project.Name | ToLower | Replace "[^a-zA-Z0-9]" "-"}'
    patch: |-
      - op: replace
        path: /metadata/labels/environment
        value: development
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: '#{ArgoCD.Project.Name | ToLower | Replace "[^a-zA-Z0-9]" "-"}'
    patch: |-
      - op: replace
        path: /metadata/name
        value: '#{ArgoCD.Project.Name | ToLower | Replace "[^a-zA-Z0-9]" "-"}-development'